---
settings:
  name: Astra Family
  search: astra-control-service,astra-control-center,astra-automation,trident
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: zh-cn,us-en,ja-jp,ko-kr,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Astra 产品系列文档
    url: "/index.html"
